/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "nsx_rpc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(NsxPingRequest, NsxPingRequest, AUTO)


PB_BIND(NsxPingResponse, NsxPingResponse, AUTO)


PB_BIND(NsxInferRequest, NsxInferRequest, 4)


PB_BIND(NsxInferResponse, NsxInferResponse, AUTO)


PB_BIND(NsxStatusRequest, NsxStatusRequest, AUTO)


PB_BIND(NsxStatusResponse, NsxStatusResponse, AUTO)


PB_BIND(NsxRpcMessage, NsxRpcMessage, 4)
