/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_NSX_RPC_PB_H_INCLUDED
#define PB_NSX_RPC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _NsxRpcMsgType {
    NsxRpcMsgType_NSX_MSG_PING_REQ = 0,
    NsxRpcMsgType_NSX_MSG_PING_RESP = 1,
    NsxRpcMsgType_NSX_MSG_INFER_REQ = 2,
    NsxRpcMsgType_NSX_MSG_INFER_RESP = 3,
    NsxRpcMsgType_NSX_MSG_STATUS_REQ = 4,
    NsxRpcMsgType_NSX_MSG_STATUS_RESP = 5
} NsxRpcMsgType;

/* Struct definitions */
/* Ping — round-trip latency test. */
typedef struct _NsxPingRequest {
    uint32_t seq;
} NsxPingRequest;

typedef struct _NsxPingResponse {
    uint32_t seq;
    uint32_t uptime_ms;
} NsxPingResponse;

typedef PB_BYTES_ARRAY_T(32000) NsxInferRequest_input_t;
/* Inference — host sends 16000 int16 LE (1 s @ 16 kHz). kws_uart runs
   KwsApp; this is not the usb_rpc 5-class toy. */
typedef struct _NsxInferRequest {
    uint32_t model_id;
    NsxInferRequest_input_t input; /* max_size set in .options */
} NsxInferRequest;

typedef PB_BYTES_ARRAY_T(32) NsxInferResponse_label_t;
typedef struct _NsxInferResponse {
    uint32_t model_id;
    uint32_t class_id;
    float confidence;
    NsxInferResponse_label_t label; /* max_size set in .options */
} NsxInferResponse;

/* Status — device reports identity and runtime stats. */
typedef struct _NsxStatusRequest {
    uint32_t reserved;
} NsxStatusRequest;

typedef PB_BYTES_ARRAY_T(32) NsxStatusResponse_board_name_t;
typedef struct _NsxStatusResponse {
    uint32_t firmware_version;
    uint32_t free_heap_bytes;
    NsxStatusResponse_board_name_t board_name; /* max_size set in .options */
} NsxStatusResponse;

/* Top-level envelope — one of the above nested as a oneof. */
typedef struct _NsxRpcMessage {
    NsxRpcMsgType type;
    pb_size_t which_payload;
    union {
        NsxPingRequest ping_req;
        NsxPingResponse ping_resp;
        NsxInferRequest infer_req;
        NsxInferResponse infer_resp;
        NsxStatusRequest status_req;
        NsxStatusResponse status_resp;
    } payload;
} NsxRpcMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _NsxRpcMsgType_MIN NsxRpcMsgType_NSX_MSG_PING_REQ
#define _NsxRpcMsgType_MAX NsxRpcMsgType_NSX_MSG_STATUS_RESP
#define _NsxRpcMsgType_ARRAYSIZE ((NsxRpcMsgType)(NsxRpcMsgType_NSX_MSG_STATUS_RESP+1))







#define NsxRpcMessage_type_ENUMTYPE NsxRpcMsgType


/* Initializer values for message structs */
#define NsxPingRequest_init_default              {0}
#define NsxPingResponse_init_default             {0, 0}
#define NsxInferRequest_init_default             {0, {0, {0}}}
#define NsxInferResponse_init_default            {0, 0, 0, {0, {0}}}
#define NsxStatusRequest_init_default            {0}
#define NsxStatusResponse_init_default           {0, 0, {0, {0}}}
#define NsxRpcMessage_init_default               {_NsxRpcMsgType_MIN, 0, {NsxPingRequest_init_default}}
#define NsxPingRequest_init_zero                 {0}
#define NsxPingResponse_init_zero                {0, 0}
#define NsxInferRequest_init_zero                {0, {0, {0}}}
#define NsxInferResponse_init_zero               {0, 0, 0, {0, {0}}}
#define NsxStatusRequest_init_zero               {0}
#define NsxStatusResponse_init_zero              {0, 0, {0, {0}}}
#define NsxRpcMessage_init_zero                  {_NsxRpcMsgType_MIN, 0, {NsxPingRequest_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define NsxPingRequest_seq_tag                   1
#define NsxPingResponse_seq_tag                  1
#define NsxPingResponse_uptime_ms_tag            2
#define NsxInferRequest_model_id_tag             1
#define NsxInferRequest_input_tag                2
#define NsxInferResponse_model_id_tag            1
#define NsxInferResponse_class_id_tag            2
#define NsxInferResponse_confidence_tag          3
#define NsxInferResponse_label_tag               4
#define NsxStatusRequest_reserved_tag            1
#define NsxStatusResponse_firmware_version_tag   1
#define NsxStatusResponse_free_heap_bytes_tag    2
#define NsxStatusResponse_board_name_tag         3
#define NsxRpcMessage_type_tag                   1
#define NsxRpcMessage_ping_req_tag               2
#define NsxRpcMessage_ping_resp_tag              3
#define NsxRpcMessage_infer_req_tag              4
#define NsxRpcMessage_infer_resp_tag             5
#define NsxRpcMessage_status_req_tag             6
#define NsxRpcMessage_status_resp_tag            7

/* Struct field encoding specification for nanopb */
#define NsxPingRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   seq,               1)
#define NsxPingRequest_CALLBACK NULL
#define NsxPingRequest_DEFAULT NULL

#define NsxPingResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   seq,               1) \
X(a, STATIC,   REQUIRED, UINT32,   uptime_ms,         2)
#define NsxPingResponse_CALLBACK NULL
#define NsxPingResponse_DEFAULT NULL

#define NsxInferRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   model_id,          1) \
X(a, STATIC,   REQUIRED, BYTES,    input,             2)
#define NsxInferRequest_CALLBACK NULL
#define NsxInferRequest_DEFAULT NULL

#define NsxInferResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   model_id,          1) \
X(a, STATIC,   REQUIRED, UINT32,   class_id,          2) \
X(a, STATIC,   REQUIRED, FLOAT,    confidence,        3) \
X(a, STATIC,   REQUIRED, BYTES,    label,             4)
#define NsxInferResponse_CALLBACK NULL
#define NsxInferResponse_DEFAULT NULL

#define NsxStatusRequest_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   reserved,          1)
#define NsxStatusRequest_CALLBACK NULL
#define NsxStatusRequest_DEFAULT NULL

#define NsxStatusResponse_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   firmware_version,   1) \
X(a, STATIC,   REQUIRED, UINT32,   free_heap_bytes,   2) \
X(a, STATIC,   REQUIRED, BYTES,    board_name,        3)
#define NsxStatusResponse_CALLBACK NULL
#define NsxStatusResponse_DEFAULT NULL

#define NsxRpcMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    type,              1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ping_req,payload.ping_req),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ping_resp,payload.ping_resp),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,infer_req,payload.infer_req),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,infer_resp,payload.infer_resp),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,status_req,payload.status_req),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,status_resp,payload.status_resp),   7)
#define NsxRpcMessage_CALLBACK NULL
#define NsxRpcMessage_DEFAULT NULL
#define NsxRpcMessage_payload_ping_req_MSGTYPE NsxPingRequest
#define NsxRpcMessage_payload_ping_resp_MSGTYPE NsxPingResponse
#define NsxRpcMessage_payload_infer_req_MSGTYPE NsxInferRequest
#define NsxRpcMessage_payload_infer_resp_MSGTYPE NsxInferResponse
#define NsxRpcMessage_payload_status_req_MSGTYPE NsxStatusRequest
#define NsxRpcMessage_payload_status_resp_MSGTYPE NsxStatusResponse

extern const pb_msgdesc_t NsxPingRequest_msg;
extern const pb_msgdesc_t NsxPingResponse_msg;
extern const pb_msgdesc_t NsxInferRequest_msg;
extern const pb_msgdesc_t NsxInferResponse_msg;
extern const pb_msgdesc_t NsxStatusRequest_msg;
extern const pb_msgdesc_t NsxStatusResponse_msg;
extern const pb_msgdesc_t NsxRpcMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define NsxPingRequest_fields &NsxPingRequest_msg
#define NsxPingResponse_fields &NsxPingResponse_msg
#define NsxInferRequest_fields &NsxInferRequest_msg
#define NsxInferResponse_fields &NsxInferResponse_msg
#define NsxStatusRequest_fields &NsxStatusRequest_msg
#define NsxStatusResponse_fields &NsxStatusResponse_msg
#define NsxRpcMessage_fields &NsxRpcMessage_msg

/* Maximum encoded size of messages (where known) */
#define NSX_RPC_PB_H_MAX_SIZE                    NsxRpcMessage_size
#define NsxInferRequest_size                     32020
#define NsxInferResponse_size                    51
#define NsxPingRequest_size                      6
#define NsxPingResponse_size                     12
#define NsxRpcMessage_size                       32030
#define NsxStatusRequest_size                    6
#define NsxStatusResponse_size                   46

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
