#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Embed a 16 kHz mono PCM clip as a C array for the flash-clip AudioSource.

Default source is tests/golden/synthetic.txt (committed, 1 s, GATE-4 golden).
A spoken WAV from the validation corpus can replace it:

  python3 tools/embed_clip.py --wav host/corpus/yes.wav

Writes audio/generated/kws_clip_data.h and kws_clip_data.cc. The .cc is
gitignored (mechanical hex); the header carries SHA256 + sample count.
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

ZOO = Path(__file__).resolve().parents[1]
DEFAULT_GOLDEN = ZOO / "kws_core" / "tests" / "golden" / "synthetic.txt"
OUT_DIR = ZOO / "kws_clip" / "audio" / "generated"


def load_golden(path: Path) -> tuple[str, list[int]]:
    lines = path.read_text().splitlines()
    name, n_s, _frames, _coeff = lines[0].split()
    n = int(n_s)
    pcm = [int(x) for x in lines[1 : 1 + n]]
    if len(pcm) != n:
        raise ValueError(f"{path}: expected {n} samples, got {len(pcm)}")
    return name, pcm


def load_wav(path: Path) -> tuple[str, list[int]]:
    sys.path.insert(0, str(ZOO / "kws_uart" / "host"))
    from stream_wav import load_wav as load_wav_bytes  # noqa: WPS433

    raw = load_wav_bytes(path)
    pcm = [
        int.from_bytes(raw[i : i + 2], "little", signed=True)
        for i in range(0, len(raw) - 1, 2)
    ]
    return path.stem, pcm


def sha256_pcm(pcm: list[int]) -> str:
    blob = b"".join(int(s).to_bytes(2, "little", signed=True) for s in pcm)
    return hashlib.sha256(blob).hexdigest()


def emit_header(path: Path, name: str, n: int, sha: str, source: str) -> None:
    path.write_text(
        "\n".join(
            [
                "// SPDX-License-Identifier: Apache-2.0",
                "// Generated by tools/embed_clip.py. Do not edit.",
                f"// source: {source}",
                "#ifndef KWS_CLIP_DATA_H_",
                "#define KWS_CLIP_DATA_H_",
                "",
                '#include "config/kws_config.h"',
                "",
                f"#define KWS_CLIP_N_SAMPLES {n}",
                f'#define KWS_CLIP_NAME "{name}"',
                f'#define KWS_CLIP_SHA256 "{sha}"',
                "",
                "#ifdef __cplusplus",
                'extern "C" {',
                "#endif",
                f"extern const AudioSample kws_clip_pcm[KWS_CLIP_N_SAMPLES];",
                "#ifdef __cplusplus",
                "}",
                "#endif",
                "#endif  // KWS_CLIP_DATA_H_",
                "",
            ]
        )
    )


def emit_cc(path: Path, pcm: list[int]) -> None:
    cols = 12
    rows: list[str] = []
    for i in range(0, len(pcm), cols):
        chunk = pcm[i : i + cols]
        rows.append("    " + ", ".join(f"{s:6d}" for s in chunk) + ",")
    body = "\n".join(rows)
    path.write_text(
        "\n".join(
            [
                "// SPDX-License-Identifier: Apache-2.0",
                "// Generated by tools/embed_clip.py. Do not edit.",
                '#include "audio/generated/kws_clip_data.h"',
                "",
                "const AudioSample kws_clip_pcm[KWS_CLIP_N_SAMPLES] = {",
                body,
                "};",
                "",
            ]
        )
    )


def parse_generated_cc(path: Path) -> list[int]:
    text = path.read_text()
    start = text.find("{")
    end = text.rfind("}")
    if start < 0 or end < 0:
        raise ValueError(f"{path}: no array body")
    nums = []
    for tok in text[start + 1 : end].replace("\n", " ").split(","):
        tok = tok.strip()
        if tok:
            nums.append(int(tok))
    return nums


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--golden", type=Path, default=None)
    ap.add_argument("--wav", type=Path, default=None)
    ap.add_argument("--out-dir", type=Path, default=OUT_DIR)
    args = ap.parse_args()
    if args.wav is not None:
        name, pcm = load_wav(args.wav)
        source = str(args.wav.relative_to(ZOO)) if args.wav.is_relative_to(ZOO) else str(args.wav)
    else:
        golden = args.golden if args.golden is not None else DEFAULT_GOLDEN
        name, pcm = load_golden(golden)
        source = str(golden.relative_to(ZOO)) if golden.is_relative_to(ZOO) else str(golden)

    sha = sha256_pcm(pcm)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    hdr = args.out_dir / "kws_clip_data.h"
    cc = args.out_dir / "kws_clip_data.cc"
    emit_header(hdr, name, len(pcm), sha, source)
    emit_cc(cc, pcm)
    roundtrip = parse_generated_cc(cc)
    if roundtrip != pcm:
        raise SystemExit("generated C array does not round-trip the source PCM")
    print(f"wrote {hdr} and {cc}  name={name} n={len(pcm)} sha256={sha}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
